### ISSUE TITLE
PhET-iO Design Review, Round 2 -- Atom & Symbol Screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-an-atom#265]
Continuation of #260 for the 1.7 release.

- [x] Uninstrument `atomCenterMarker`, if possible. Otherwise, `atomCenterMarker.visibleProperty` should be `phetioReadOnly: true`.
- [x] Uninstrument the `particleNode` child of every electron, proton, and neutron. It's not included in state and contains no useful information for instructional designers, so we can likely prune it from the tree.
- [x] Make `zLayerProperty` read-only. There is no reason for this to be client-controlled, and it could likely lead to buggy behavior.
- [x] https://github.com/phetsims/build-an-atom/issues/284
- [x] Create `view.buckets` grouping to house all of the bucket drag listeners. Once we support alt input, the keyboard drag listeners will add even more clutter, so having additional organization in the tree would be helpful.
- [x] Add the following linked properties to make the model data easier to find in the view.
  - [x] `massNumberAccordionBox`: Link to `massNumberProperty`
  - [x] `netChargeAccordionBox`: Link to `netChargeProperty` (renamed from `chargeProperty` above)
  - [x] `periodicTableAccordionBox`: Link to `elementNameStringProperty`
  - [x] `particleCountsDisplay`: Link to `model.particleCounts` grouping. 
  * Note: the Symbol is associated with a lot of data (mass number, charge, element name, number of protons). I think it's overkill to link to all four of those Properties, so I decided against adding links to the Symbol AccordionBox.
- <s>Instrument `visibleProperty` of `atomNode`.  @Nancy-Salpepi noted in the design doc that hiding the atom could support prediction-making about the atom based on its mass/charge or symbol. </s>
    - <s>Feature `atomNode.visibleProperty`</s>
    - After discussion with @jbphet and @Nancy-Salpepi, we decided to remove this request. The AtomNode does not include the particles, so it would take considerable effort to achieve the desired behavior. The use case is somewhat hypothetical so this work didn't seem worthwhile.

@jbphet please let me know if you have any questions or concerns about these requests.

**Comment by AgustinVallejo** [comment]
All these have been addressed, except the one of name changing, which has been moved to its own issue. Asigning back to review.

**Comment by arouinfar** [comment]
@AgustinVallejo something's still not quite hooked up correctly. I've pulled all and cleared my cache twice.  When selecting `model.atom.particleCounts` in the tree, nothing appears in the panel under the sim, which generally means it's not an instrumented element.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo! Closing (finally).
