### ISSUE TITLE
Game Screen: Updates to ChallengeViews

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-an-atom#294]
For #287 

@Nancy-Salpepi and I are finding several things to uninstrument and add as we review the Game Screen. We'll add to this list as the review continues. Last designer to unassign themselves will reassign this issue to the devs.

### Items to uninstrument
In general, we want to uninstrument non-interactive parts of the challenge views as well as any `visibleProperty` that would make the game unplayable when `false`.

- [x] The top-level `visibleProperty` under each challenge view. The value is always `true` even if it's not the challenge type currently displayed, which is buggy.
- [x] `schematic*ChallengeView.noninteractiveSchematicAtomNode`
- [x] `symbolToCountsChallengeView.electronRowNode`
- [x] `symbolToCountsChallengeView.neutronRowNode`
- [x] `symbolToCountsChallengeView.protonRowNode`
- [x] `symbolToCountsChallengeView.particleCountsNode`
- [x] `symbolToSchematicChallengeView.interactiveSchematicAtom.visibleProperty`
- [x] `symbolToSchematicChallengeView.interactiveSchematicAtom.atomNode`
- [x] `*ToElementChallengeView.neutralOrIonRadioButtons.ionRadioButton.visibleProperty`
- [x] `*ToElementChallengeView.neutralOrIonRadioButtons.neutralAtomRadioButton.visibleProperty`
- [x]  `symbolTo*ChallengeView.interactiveSymbolNode` and all of its children. The symbol is not interactive in the `symbolTo` challenge types.
- [x] `questionPromptText`

### Items to instrument

- [x] Under `symbolToSchematicChallengeView` add `protonCountProperty`, `neutronCountProperty`, and `electronCountProperty` so that it is possible to know the amount of each particle the user selected/added.
  - [x] Keeping consistent with #295, provide phetioDocumentation for these properties in the form: "{{Particle Type}} count entered by the user."[/+][-] [ ] Keeping consistent with #295, provide phetioDocumentation for these properties in the form: "{{Particle Type}} count entered by the user."

**Comment by AgustinVallejo** [comment]
I implemented all this except https://github.com/phetsims/build-an-atom/issues/308 which I moved into a sub-issue (cool, right?).

Feel free to review the rest @arouinfar

**Comment by arouinfar** [comment]
@Nancy-Salpepi can you please also review the Challenge Views?

**Comment by arouinfar** [comment]
@AgustinVallejo looks like you missed the `protonRowNode` so I unchecked it above. 

All the other changes look good to me, but I would like to take another pass through the challenge views to make sure there isn't anything else we missed.

**Comment by Nancy-Salpepi** [comment]
It looks like `interactiveSymbolNode` was uninstrumented for all challenges rather than just the ones that started with `symbolTo...`

All the challenges where users need to solve for part or all of the symbol should to have interactiveSymbolNode instrumented. 

- [ ] countsToSymbolAllChallengeView.interactiveSymbolNode
- [ ] countsToSymbolChargeChallengeView.interactiveSymbolNode
- [ ] countsToSymbolMassNumberChallengeView.interactiveSymbolNode
- [ ] schematicToSymbolAllChallengeView.interactiveSymbolNode
- [ ] schematicToSymbolChargeChallengeView.interactiveSymbolNode
- [ ] schematicToSymbolMassNumberChallengeView.interactiveSymbolNode
- [ ] schematicToSymbolProtonCountChallengeView.interactiveSymbolNode

**Comment by AgustinVallejo** [comment]
This is done. Back for review @arouinfar @Nancy-Salpepi

**Comment by arouinfar** [comment]
Good catch, thanks @Nancy-Salpepi! Updates look good on main @AgustinVallejo, closing.
