### ISSUE TITLE
Enter key does not exist on macOS.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#428]
Related to https://github.com/phetsims/scenery-phet/issues/953 ...

Descriptions should not be using "Enter", it does not exist on macOS.  Instead, a placeholder should be filled in with the value of `TextKeyNode.getEnterKeyString`.

There is at least 1 case in this sim:

```
      grabOrReleaseDescription: Grab or release particle with Space or Enter keys.
```

See `BasicActionsKeyboardHelpSection` for example usage of `TextKeyNode.getEnterKeyString`.

**Comment by jbphet** [comment]
I started looking into this problem, and it seemed like @jessegreenberg had fixed it by moving support into common code.  This looked like the relevant commit:

https://github.com/phetsims/scenery-phet/commit/ad50de2c51c86a4f27e605c4434ab581d7b25bf1

I thought I'd verify the behavior by testing BAA on a Mac, and was surprised to see that it seems fixed in the dialog but not in the description.  Here's a screenshot:

<img width="1183" height="611" alt="Image" src="https://github.com/user-attachments/assets/ddfe4574-bc0a-43cd-9779-83c41227af6f" />

@jessegreenberg - Is there a problem in the common code (scenery-phet), or am I somehow setting things up incorrectly in BAA?

**Comment by jessegreenberg** [comment]
Sorry about that, thank you! Looks like I forgot about this in https://github.com/phetsims/scenery-phet/issues/933, I will take a look over there and then report back.

**Comment by jessegreenberg** [comment]
This should be resolved with https://github.com/phetsims/scenery-phet/issues/933. @jbphet can you please confirm?

**Comment by jessegreenberg** [comment]
I *think* this is a case of Safari caching things strangely. I tried many changes and nothing seemed to work. I was able to put in `debugger`/`console.log` statements and see them in Safari - so I thought the cache was nice and busted! But no matter what I did, I always saw "Enter" in that description on Safari. Further more, no matter *what* I tried to insert into that string pattern, I never saw it respect the value. But if I removed the `labelInnerContent` entirely, I could see the whole description disappear.

Then I deleted caches (Develop -> Empty Caches) and all the problems went away.

@jbphet can you please confirm this on your Mac?

**Comment by jbphet** [comment]
Wow, that's crazy.  I tried the Empty Caches thing on the Mac that I'm using, and it still didn't fix the problem, but I tried loading on both Chrome and Firefox on that Mac and the value was correct, i.e. it said "Return".  I went back to Safari and restarted it and then emptied that caches, and "Return" finally showed up.  Man, that is some odd and persistent caching!

Thanks for looking at this @jessegreenberg, and I think we're good to go.  Closing.
